#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/pcs-uiconfig-dotnet"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

# The version is stored in a file, to avoid hardcoding it in multiple places
APP_VERSION=$(cat "$APP_HOME/version")

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

    # Some settings are used to connect to an external dependency, e.g. Azure IoT Hub and IoT Hub Manager API
    # Depending on which settings and which dependencies are needed, edit the list of variables
    echo "Starting UIConfig ..."
    docker run -it -p $PCS_UICONFIG_WEBSERVICE_PORT:$PCS_UICONFIG_WEBSERVICE_PORT \
        -e "PCS_UICONFIG_WEBSERVICE_PORT=$PCS_UICONFIG_WEBSERVICE_PORT" \
        "$DOCKER_IMAGE:$APP_VERSION"
}

run_container

set +e
